version: '3.8'

services:
  db:
    image: postgres 
    container_name: go-tasks
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abdullah
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  go:
    container_name: golang
    build:
      context: .
    depends_on: 
      db:
        condition: service_healthy

volumes:
  db_data: